# hyperparameters for model

models: # 需要1个时只保留一行即可，保证list格式
  # - deepseek-chat
  - azure-gpt-4o-2024-08-06
  # - claude-3-5-sonnet-20241022

max_tokens: 1024

temperature: 0.0

system_prompt: ｜
  你是一名小说写作专家，你会根据用户的要求进行创作。

prompt_template: |
  ### command ###
  ### question ###
  {0}
  ### answer ###
  {1}

# 以下为数据集的列名，按照你的数据集列名填写
input_columns: # 按prompt_template注入的顺序填写列名
  - question
  - answer

# 暂时放弃
# history_columns: # 按你提供的一行数据多轮历史的列名填写
#   - round0
#   - round1